version: '3.4'

services:

  sql-identity:
    image: postgres

  sql-library:
    image: mcr.microsoft.com/azure-sql-edge

  pgadmin:
    image: dpage/pgadmin4
    depends_on:
      - sql-identity

  travel.aggregator:
    image: ${DOCKER_REGISTRY-}aggregator
    build:
      context: .
      dockerfile: src/Travel.BBf/Travel.Aggregator/Dockerfile

  identity.api:
    image: ${DOCKER_REGISTRY-}identity
    build:
      context: .
      dockerfile: src/Travel.Services/Identity/Identity.Api/Dockerfile

  library.api:
    image: ${DOCKER_REGISTRY-}library
    build:
      context: .
      dockerfile: src/Travel.Services/Library/Library.Api/Dockerfile

 # travel.web:
 #   image: ${DOCKER_REGISTRY-}travel
 #   build:
 #     context: .
 #     dockerfile: src/Travel.Web/travelweb/Dockerfile
 #     args:
 #       - REACT_APP_ROUTE_API_IDENTITY=${IDENTITY_URL}
 #       - REACT_APP_ROUTE_API_AGGREGATOR=$http://{DNS_DOCKER_TRAVEL_IP}:5010